# docker-compose.db.yml
services:
  db:
    image: postgres:16
    container_name: citas_db
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_OWNER}
      POSTGRES_PASSWORD: ${DB_OWNER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TZ}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_OWNER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 12

volumes:
  db_data: